### PR TITLE
Migrate to enableEdgeToEdge() function

### PR DESCRIPTION
**Pull request by Omico**

### CODE REVIEW

**Comment by chrisbanes** [comment]
The `enableEdgeToEdge()` function is a convenience function, which ends up needing more code (#1689) to achieve the same thing.

I'm not going to merge this or #1689 as there is no real benefit, only more code.

Thanks for spending the time though!

**Comment by Omico** [comment]
> I'm not going to merge this or https://github.com/chrisbanes/tivi/pull/1689 as there is no real benefit, only more code.

For #1689, The status bar won't change to the light style after manually changing to the dark theme. So we have to add these codes.

**Review by chrisbanes — APPROVED** [review]

**Comment by itsandreramon** [comment]
What's the reason you changed your mind?

**Comment by chrisbanes** [comment]
I want to refactor the code, but this does fix an issue with button navigation bars. I personally don't use it, but that doesn't mean it shouldn't be fixed.

**Comment by chrisbanes** [comment]
Thanks for the contribution @Omico!

**Pull request merged**
