### PR TITLE
Fix TraktAuthModule compile error

### PR DESCRIPTION
**Pull request by alishari**
As I have described the problem https://github.com/chrisbanes/tivi/issues/747, there was a problem in compiling code. current code called AuthorizationServiceConfiguration with three parameters but it has constructors with two or four parameters.

### CODE REVIEW

**Comment by alishari** [comment]
@googlebot I fixed it.

**Comment by alishari** [comment]
CI task failed due to an error in uploading Crashlytics mapping which is not related to this commint:

```
Execution failed for task ':app:uploadCrashlyticsMappingFileRelease'.
> java.io.IOException: Unknown error while sending file, check network [/home/runner/work/tivi/tivi/app/build/crashlytics/Release/mappings/b7c898f0f8834136ab107d140cd48513.gz; response: 400 HTTP/1.1 400 Bad Request]
```

**Comment by alishari** [comment]
@googlebot I fixed it.

**Comment by chrisbanes** [comment]
Thanks for the PR! Looks like https://github.com/openid/AppAuth-Android/pull/525 caused an API break. I've pinned our AppAuth dependency to a specific revision (ea4dc202407a5ea3d2c9748569374bfd848bc2b2) so we don't hit this in the future.

**Pull request merged**
