### PR TITLE
Save carousel's scroll position in DisCoverFragment

### PR DESCRIPTION
**Pull request by Nghicv**
Fix issue: https://github.com/chrisbanes/tivi/issues/481

### CODE REVIEW

**Comment by Nghicv** [comment]
@googlebot I signed it!

**Comment by chrisbanes** [comment]
Thanks!

**Comment by chrisbanes** [comment]
Getting the following crash with the change:

```
Fatal Exception: java.lang.IllegalStateException: State cannot be restored once views have been bound. It should be done before adding the adapter to the recycler view.
       at com.airbnb.epoxy.BaseEpoxyAdapter.onRestoreInstanceState(BaseEpoxyAdapter.java:226)
       at com.airbnb.epoxy.EpoxyController.onRestoreInstanceState(EpoxyController.java:702)
       at app.tivi.home.discover.DiscoverFragment.onCreateView(DiscoverFragment.java:65)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2669)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1321)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2693)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1346)
       at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2515)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2290)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2246)
```

Need to look into why, but for now I've reverted the change.

**Comment by Nghicv** [comment]
Sorry
How can we reproduce this crash?
Should we reopen the issue https://github.com/chrisbanes/tivi/issues/481?

**Comment by chrisbanes** [comment]
No worries. Yep, re-opened.

**Pull request merged**
